title: blank
first_name: Avaljot
middle_name: 
last_name: Singh
email: avaljot2@illinois.edu
description: 
footer_text: |
  
keywords: academic-website, portfolio-website
lang: en
icon: 
url: https://avaljotsingh.github.io
baseurl: 
last_updated: false
impressum_path: null
repo_theme_light: default
repo_theme_dark: dark
repo_trophies:
  enabled: true
  theme_light: flat
  theme_dark: gitdimmed
rss_icon: false
navbar_fixed: true
footer_fixed: true
max_width: 800px
serve_og_meta: false
serve_schema_org: false
og_image: null
github_username: null
gitlab_username: null
twitter_username: singhasAvaljot
mastodon_username: null
linkedin_username: avaljot-singh
telegram_username: null
scholar_userid: null
semanticscholar_id: null
whatsapp_number: null
orcid_id: null
medium_username: null
quora_username: null
publons_id: null
lattes_id: null
osf_id: null
research_gate_profile: null
scopus_id: null
blogger_url: null
work_url: null
keybase_username: null
wikidata_id: null
wikipedia_id: null
dblp_url: null
stackoverflow_id: null
kaggle_id: null
lastfm_id: null
spotify_id: null
pinterest_id: null
unsplash_id: null
instagram_id: null
facebook_id: null
youtube_id: null
discord_id: null
zotero_username: null
wechat_qr: null
contact_note: |
  You can even add a little note about which of these is the best way to reach you.
google_analytics: null
cronitor_analytics: null
google_site_verification: null
bing_site_verification: null
blog_name: al-folio
blog_nav_title: 
blog_description: a simple whitespace theme for academics
permalink: /blog/:year/:title/
pagination:
  enabled: true
related_blog_posts:
  enabled: true
  max_related: 5
giscus:
  repo: alshedivat/al-folio
  category: Comments
  mapping: title
  strict: 1
  reactions_enabled: 1
  input_position: bottom
  theme: preferred_color_scheme
  emit_metadata: 0
  lang: en
disqus_shortname: al-folio
external_sources:
  - name: medium.com
    rss_url: https://medium.com/@al-folio/feed
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:path/
  projects:
    output: true
    permalink: /projects/:path/
  teaching:
    output: true
    permalink: /teaching/:path/
announcements:
  enabled: true
  scrollable: true
  limit: 5
latest_posts:
  enabled: true
  scrollable: true
  limit: 3
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
include:
  - _pages
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
keep_files:
  - CNAME
  - .nojekyll
  - .git
plugins:
  - jekyll-archives
  - jekyll-diagrams
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-get-json
  - jekyll-imagemagick
  - jekyll-jupyter-notebook
  - jekyll-link-attributes
  - jekyll-minifier
  - jekyll-paginate-v2
  - jekyll/scholar
  - jekyll-sitemap
  - jekyll-toc
  - jekyll-twitter-plugin
  - jemoji
defaults:
  - scope:
      path: assets
    values:
      sitemap: false
sass:
  style: compressed
jekyll-minifier:
  exclude:
    - robots.txt
  uglifier_args:
    harmony: true
jekyll-archives:
  enabled:
    - year
    - tags
    - categories
  layouts:
    year: archive-year
    tag: archive-tag
    category: archive-category
  permalinks:
    year: /blog/:year/
    tag: /blog/tag/:name/
    category: /blog/category/:name/
display_tags:
  - formatting
  - images
  - links
  - math
  - code
display_categories:
  - blockquotes
scholar:
  last_name:
    - Einstein
  first_name:
    - Albert
    - A.
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  bibtex_filters:
    - latex
    - smallcaps
    - superscript
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details
  query: '@*'
  group_by: year
  group_order: descending
badges:
  altmetric_badge: true
  dimensions_badge: true
filtered_bibtex_keywords:
  - abbr
  - abstract
  - arxiv
  - bibtex_show
  - html
  - pdf
  - selected
  - supp
  - blog
  - code
  - poster
  - slides
  - website
  - preview
  - altmetric
max_author_limit: 3
more_authors_animation_delay: 10
external_links:
  enabled: true
  rel: external nofollow noopener
  target: _blank
  exclude: null
imagemagick:
  enabled: true
  widths:
    - 480
    - 800
    - 1400
  input_directories:
    - assets/img/
  input_formats:
    - .jpg
    - .jpeg
    - .png
    - .tiff
  output_formats:
    webp: '-resize 800x'
jekyll-diagrams: null
enable_google_analytics: false
enable_cronitor_analytics: false
enable_google_verification: false
enable_bing_verification: false
enable_masonry: true
enable_math: true
enable_tooltips: false
enable_darkmode: false
enable_navbar_social: false
enable_project_categories: true
enable_medium_zoom: true
enable_progressbar: true
bootstrap-table:
  version: 1.22.1
jquery:
  version: 3.6.0
  integrity: sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=
mathjax:
  version: 3.2.0
masonry:
  version: 4.2.2
  integrity: sha256-Nn1q/fx0H7SNLZMQ5Hw5JLaTRZp0yILA/FRexe19VdI=
mdb:
  version: 4.20.0
  integrity:
    css: sha256-jpjYvU3G3N6nrrBwXJoVEYI/0zw8htfFnhT9ljN3JJw=
    js: sha256-NdbiivsvWt7VYCt6hYNT3h/th9vSTL4EDWeGs5SN3DA=
medium_zoom:
  version: 1.0.8
  integrity: sha256-7PhEpEWEW0XXQ0k6kQrPKwuoIomz8R8IYyuU1Qew4P8=
jekyll_get_json:
  - data: resume
    json: assets/json/resume.json
jsonresume:
  - basics
  - work
  - education
  - publications
  - projects
  - volunteer
  - awards
  - certificates
  - skills
  - languages
  - interests
  - references
